version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    volumes:
      - ./elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"

  zeek:
    image: zeek/zeek:latest
    container_name: zeek
    volumes:
      - ./threat-hunting/zeek:/etc/zeek
    command: "zeek -i eth0 local"

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    volumes:
      - ./threat-hunting/suricata:/etc/suricata
    command: "suricata -i eth0"

  llm-ingestion:
    build: ./llm/ingestion
    container_name: llm-ingestion

  llm-reporting:
    build: ./llm/reporting
    container_name: llm-reporting

networks:
  default:
    driver: bridge
